REMOTE_URL:
- file:///opt/spaceone/statistics/config/database.yaml
- file:///opt/spaceone/statistics/config/shared.yaml
- file:///opt/spaceone/statistics/config/application.yaml
GLOBAL:
  MAX_WORKERS: 1000
  DATABASES:
    default:
      db: statistics
      host: mongodb
      port: 27017
      maxPoolSize: 200
      username: statistics_user
      password: statistics_password
  CACHES:
    default:
      backend: spaceone.core.cache.redis_cache.RedisCache
      host: redis
      port: 6379
      encoding: utf-8
      socket_timeout: 10
      socket_connect_timeout: 10
  LOG:
    loggers:
      spaceone:
        handlers:
          - console
          - file
    handlers:
      file:
        type: file
        filename: /var/log/spaceone/statistics.log
  CONNECTORS:
    IdentityConnector:
      endpoint:
        v1: grpc://identity:50051
    SecretConnector:
      endpoint:
        v1: grpc://secret:50051
    PluginConnector:
      endpoint:
        v1: grpc://plugin:50051
    RepositoryConnector:
      endpoint:
        v1: grpc://repository:50051
